[build]
  publish = "build"
  command = "npm run build && cd netlify/functions && npm install"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  JWT_SECRET = "gradfolio-secret-key-2024"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/u/*"
  to = "/.netlify/functions/portfolio/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"